"""empty message

Revision ID: 62197722c22b
Revises: e6c4227b693b
Create Date: 2024-07-17 13:19:30.587452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62197722c22b'
down_revision = 'e6c4227b693b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
