"""empty message

Revision ID: e7ea919f3c06
Revises: 2058cea74889
Create Date: 2024-07-17 15:44:29.198188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ea919f3c06'
down_revision = '2058cea74889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topics_addressed', sa.String(length=150), nullable=False))
        batch_op.drop_column('issues_addressed')

    with op.batch_alter_table('quiz_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topics_addressed', sa.String(length=150), nullable=False))
        batch_op.drop_column('issues_addressed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issues_addressed', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('topics_addressed')

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issues_addressed', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('topics_addressed')

    # ### end Alembic commands ###
