"""empty message

Revision ID: edc577835211
Revises: 5b8bd303f810
Create Date: 2024-07-17 19:25:38.147327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc577835211'
down_revision = '5b8bd303f810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('topics_addressed',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('quiz_response', schema=None) as batch_op:
        batch_op.alter_column('topics_addressed',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_response', schema=None) as batch_op:
        batch_op.alter_column('topics_addressed',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('topics_addressed',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
